version: '3'

services:
  wordpress:

    image: wordpress:5.1.1-php7.3-apache

    ports:

      - "8000:80"

    restart: always

    environment:

      WORDPRESS_DB_HOST: db:3306

      WORDPRESS_DB_USER: root

      WORDPRESS_DB_PASSWORD: P@ssw0rd

    working_dir: /wordpress

    volumes:

      - ./wp-content

      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:

  db_data: